// src-next/components/WatchesPanel/CreateWatchForm.tsx
import React, { useState, useCallback, useRef, useEffect } from 'react';
import type { FilterCriteria, LogLevel, CombineMode } from '../../bridge/types';
import { Button } from '../../ui';
import clsx from 'clsx';
import styles from './WatchesPanel.module.css';

interface CreateWatchFormProps {
  onSubmit: (criteria: FilterCriteria) => Promise<void>;
  onCancel: () => void;
}

const ALL_LEVELS: { key: LogLevel; label: string }[] = [
  { key: 'Verbose', label: 'V' },
  { key: 'Debug', label: 'D' },
  { key: 'Info', label: 'I' },
  { key: 'Warn', label: 'W' },
  { key: 'Error', label: 'E' },
  { key: 'Fatal', label: 'F' },
];

export const CreateWatchForm = React.memo(function CreateWatchForm({
  onSubmit,
  onCancel,
}: CreateWatchFormProps) {
  const [textSearch, setTextSearch] = useState('');
  const [regex, setRegex] = useState('');
  const [selectedLevels, setSelectedLevels] = useState<Set<LogLevel>>(new Set());
  const [tags, setTags] = useState('');
  const [pids, setPids] = useState('');
  const [combine, setCombine] = useState<CombineMode>('and');
  const [submitting, setSubmitting] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const inputRef = useRef<HTMLInputElement>(null);

  useEffect(() => {
    inputRef.current?.focus();
  }, []);

  const toggleLevel = useCallback((level: LogLevel) => {
    setSelectedLevels((prev) => {
      const next = new Set(prev);
      if (next.has(level)) next.delete(level);
      else next.add(level);
      return next;
    });
  }, []);

  const buildCriteria = useCallback((): FilterCriteria | null => {
    // Every FilterCriteria field is required (nullable) on the wire — start from
    // an all-null base and track whether the user actually set anything, since
    // an all-null criteria is meaningless to send.
    const criteria: FilterCriteria = {
      textSearch: null,
      regex: null,
      logLevels: null,
      tags: null,
      timeStart: null,
      timeEnd: null,
      pids: null,
      combine: 'and',
    };
    let anySet = false;
    if (textSearch.trim()) { criteria.textSearch = textSearch.trim(); anySet = true; }
    if (regex.trim()) { criteria.regex = regex.trim(); anySet = true; }
    if (selectedLevels.size > 0) { criteria.logLevels = Array.from(selectedLevels); anySet = true; }
    if (tags.trim()) {
      criteria.tags = tags.split(',').map((t) => t.trim()).filter(Boolean);
      anySet = true;
    }
    if (pids.trim()) {
      const parsed = pids
        .split(',')
        .map((p) => parseInt(p.trim(), 10))
        .filter((n) => !isNaN(n));
      if (parsed.length > 0) { criteria.pids = parsed; anySet = true; }
    }
    if (combine !== 'and') { criteria.combine = combine; anySet = true; }

    return anySet ? criteria : null;
  }, [textSearch, regex, selectedLevels, tags, pids, combine]);

  const handleSubmit = useCallback(async () => {
    const criteria = buildCriteria();
    if (!criteria) {
      setError('At least one filter criterion is required');
      return;
    }
    setSubmitting(true);
    setError(null);
    try {
      await onSubmit(criteria);
    } catch (e) {
      setError(String(e));
      setSubmitting(false);
    }
  }, [buildCriteria, onSubmit]);

  const handleKeyDown = useCallback(
    (e: React.KeyboardEvent) => {
      if (e.key === 'Enter' && !e.shiftKey) {
        e.preventDefault();
        handleSubmit();
      } else if (e.key === 'Escape') {
        e.preventDefault();
        onCancel();
      }
    },
    [handleSubmit, onCancel],
  );

  return (
    <div className={styles.createForm} onKeyDown={handleKeyDown}>
      {/* Row 1: text search */}
      <div className={styles.formRow}>
        <input
          ref={inputRef}
          className={styles.formInput}
          type="text"
          placeholder="Text search..."
          value={textSearch}
          onChange={(e) => setTextSearch(e.target.value)}
        />
      </div>

      {/* Row 2: levels + optional fields */}
      <div className={styles.formRow}>
        <div className={styles.levelGroup}>
          {ALL_LEVELS.map(({ key, label }) => (
            <button
              key={key}
              className={clsx(
                styles.levelToggle,
                selectedLevels.has(key) && styles.levelToggleActive,
                (key === 'Error' || key === 'Fatal') && selectedLevels.has(key) && styles.levelToggleDanger,
                key === 'Warn' && selectedLevels.has(key) && styles.levelToggleWarning,
              )}
              onClick={() => toggleLevel(key)}
              type="button"
              title={key}
            >
              {label}
            </button>
          ))}
        </div>
        <input
          className={clsx(styles.formInput, styles.formInputSmall)}
          type="text"
          placeholder="tag"
          value={tags}
          onChange={(e) => setTags(e.target.value)}
        />
        <input
          className={clsx(styles.formInput, styles.formInputSmall)}
          type="text"
          placeholder="regex"
          value={regex}
          onChange={(e) => setRegex(e.target.value)}
        />
        <input
          className={clsx(styles.formInput, styles.formInputTiny)}
          type="text"
          placeholder="pid"
          value={pids}
          onChange={(e) => setPids(e.target.value)}
        />
      </div>

      {/* Row 3: combine + actions */}
      <div className={clsx(styles.formRow, styles.formRowActions)}>
        <div className={styles.combineGroup}>
          <button
            className={clsx(styles.combineToggle, combine === 'and' && styles.combineToggleActive)}
            onClick={() => setCombine('and')}
            type="button"
          >
            AND
          </button>
          <button
            className={clsx(styles.combineToggle, combine === 'or' && styles.combineToggleActive)}
            onClick={() => setCombine('or')}
            type="button"
          >
            OR
          </button>
        </div>
        {error && <span className={styles.formError}>{error}</span>}
        <div className={styles.formActions}>
          <button className={styles.formCancelLink} onClick={onCancel} type="button">
            Cancel
          </button>
          <Button variant="primary" size="sm" onClick={handleSubmit} loading={submitting}>
            Create
          </Button>
        </div>
      </div>
    </div>
  );
});

// src-solid/watches/CreateWatchForm.tsx
/** @jsxImportSource solid-js */
import { createSignal, For, onMount } from 'solid-js';
import type { JSX } from 'solid-js';
import type { CombineMode, FilterCriteria, LogLevel } from '@bridge/types';
import styles from './watches.module.css';

export interface CreateWatchFormProps {
  onSubmit: (criteria: FilterCriteria) => Promise<void>;
  onCancel: () => void;
}

const ALL_LEVELS: { key: LogLevel; label: string }[] = [
  { key: 'Verbose', label: 'V' },
  { key: 'Debug', label: 'D' },
  { key: 'Info', label: 'I' },
  { key: 'Warn', label: 'W' },
  { key: 'Error', label: 'E' },
  { key: 'Fatal', label: 'F' },
];

/** Solid port of `src-next/components/WatchesPanel/CreateWatchForm.tsx`. Same
 *  fields, same "every `FilterCriteria` field is required (nullable) on the
 *  wire, start null and track whether anything was actually set" contract. */
export function CreateWatchForm(props: CreateWatchFormProps): JSX.Element {
  const [textSearch, setTextSearch] = createSignal('');
  const [regex, setRegex] = createSignal('');
  const [selectedLevels, setSelectedLevels] = createSignal<Set<LogLevel>>(new Set());
  const [tags, setTags] = createSignal('');
  const [pids, setPids] = createSignal('');
  const [combine, setCombine] = createSignal<CombineMode>('and');
  const [submitting, setSubmitting] = createSignal(false);
  const [error, setError] = createSignal<string | null>(null);
  let inputRef: HTMLInputElement | undefined;

  onMount(() => inputRef?.focus());

  const toggleLevel = (level: LogLevel): void => {
    setSelectedLevels((prev) => {
      const next = new Set(prev);
      if (next.has(level)) next.delete(level);
      else next.add(level);
      return next;
    });
  };

  const buildCriteria = (): FilterCriteria | null => {
    const criteria: FilterCriteria = {
      textSearch: null,
      regex: null,
      logLevels: null,
      tags: null,
      timeStart: null,
      timeEnd: null,
      pids: null,
      combine: 'and',
    };
    let anySet = false;
    if (textSearch().trim()) { criteria.textSearch = textSearch().trim(); anySet = true; }
    if (regex().trim()) { criteria.regex = regex().trim(); anySet = true; }
    if (selectedLevels().size > 0) { criteria.logLevels = Array.from(selectedLevels()); anySet = true; }
    if (tags().trim()) {
      criteria.tags = tags().split(',').map((t) => t.trim()).filter(Boolean);
      anySet = true;
    }
    if (pids().trim()) {
      const parsed = pids()
        .split(',')
        .map((p) => parseInt(p.trim(), 10))
        .filter((n) => !Number.isNaN(n));
      if (parsed.length > 0) { criteria.pids = parsed; anySet = true; }
    }
    if (combine() !== 'and') { criteria.combine = combine(); anySet = true; }
    return anySet ? criteria : null;
  };

  const handleSubmit = async (): Promise<void> => {
    const criteria = buildCriteria();
    if (!criteria) {
      setError('At least one filter criterion is required');
      return;
    }
    setSubmitting(true);
    setError(null);
    try {
      await props.onSubmit(criteria);
    } catch (e) {
      setError(String(e));
      setSubmitting(false);
    }
  };

  const handleKeyDown = (e: KeyboardEvent): void => {
    if (e.key === 'Enter' && !e.shiftKey) {
      e.preventDefault();
      void handleSubmit();
    } else if (e.key === 'Escape') {
      e.preventDefault();
      props.onCancel();
    }
  };

  const levelClass = (key: LogLevel): string =>
    [
      styles.levelToggle,
      selectedLevels().has(key) && styles.levelToggleActive,
      (key === 'Error' || key === 'Fatal') && selectedLevels().has(key) && styles.levelToggleDanger,
      key === 'Warn' && selectedLevels().has(key) && styles.levelToggleWarning,
    ]
      .filter(Boolean)
      .join(' ');

  return (
    <div class={styles.createForm} onKeyDown={handleKeyDown} data-testid="create-watch-form">
      <div class={styles.formRow}>
        <input
          ref={inputRef}
          class={styles.formInput}
          type="text"
          placeholder="Text search…"
          value={textSearch()}
          onInput={(e) => setTextSearch(e.currentTarget.value)}
        />
      </div>

      <div class={styles.formRow}>
        <div class={styles.levelGroup}>
          <For each={ALL_LEVELS}>
            {({ key, label }) => (
              <button
                type="button"
                class={levelClass(key)}
                onClick={() => toggleLevel(key)}
                title={key}
              >
                {label}
              </button>
            )}
          </For>
        </div>
        <input
          class={`${styles.formInput} ${styles.formInputSmall}`}
          type="text"
          placeholder="tag"
          value={tags()}
          onInput={(e) => setTags(e.currentTarget.value)}
        />
        <input
          class={`${styles.formInput} ${styles.formInputSmall}`}
          type="text"
          placeholder="regex"
          value={regex()}
          onInput={(e) => setRegex(e.currentTarget.value)}
        />
        <input
          class={`${styles.formInput} ${styles.formInputTiny}`}
          type="text"
          placeholder="pid"
          value={pids()}
          onInput={(e) => setPids(e.currentTarget.value)}
        />
      </div>

      <div class={`${styles.formRow} ${styles.formRowActions}`}>
        <div class={styles.combineGroup}>
          <button
            type="button"
            class={`${styles.combineToggle} ${combine() === 'and' ? styles.combineToggleActive : ''}`}
            onClick={() => setCombine('and')}
          >
            AND
          </button>
          <button
            type="button"
            class={`${styles.combineToggle} ${combine() === 'or' ? styles.combineToggleActive : ''}`}
            onClick={() => setCombine('or')}
          >
            OR
          </button>
        </div>
        {error() && <span class={styles.formError}>{error()}</span>}
        <div class={styles.formActions}>
          <button type="button" class={styles.formCancelLink} onClick={() => props.onCancel()}>
            Cancel
          </button>
          <button
            type="button"
            class={styles.primaryButtonSm}
            onClick={() => void handleSubmit()}
            disabled={submitting()}
          >
            {submitting() ? 'Creating…' : 'Create'}
          </button>
        </div>
      </div>
    </div>
  );
}
